version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fatawa-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dyvi15hnl9ei"
s3_prefix = "fatawa-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true

[Prod]
[Prod.deploy]
[Prod.deploy.parameters]
stack_name = "fatawa-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dyvi15hnl9ei"
s3_prefix = "fatawa-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
